### ISSUE TITLE
Fix delete_history_from_library_context_menu test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2793]
Can not reproduce failure described at step: "Mozilla page is displayed in the History list successfully. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:
--
>> Traceback (most recent call last):                                                                       
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>                
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                              
>>     run_iris()                                                                                           
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                         
>>     run(master_test_list, tests, browser)                                                                
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                            
>>     current.run()                                                                                        
>>   File "/Users/dev/iris/iris/tests/history/delete_history_from_library_context_menu.py", line 52, in run 
>>     assert_true(self, expected_4, 'Mozilla page is displayed in the History list successfully.')         
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                        
>>     assert_equal(test_case, actual, True, message)                                                       
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                       
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.

**Comment by pavelciapa** [comment]
Failed on win10 due to logic or pattern reason
![2019_08_05_11_54_30_484251_not_found](https://user-images.githubusercontent.com/45387203/62517959-f5da6500-b817-11e9-8f04-35e6347a1716.jpg)
