### ISSUE TITLE
Fix position_window_restored test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2925]
The test fails at step: "None - [Actual]: None [Expected]: None" for Win 7

**Comment by pavelciapa** [comment]
Fails on Step 5

Creating of incorrect region
![2019_04_19_11_07_53_444073_position_window_restored](https://user-images.githubusercontent.com/45387203/56567379-748af980-65bd-11e9-8f81-1a83e0b89355.jpg)


![2019_04_19_11_07_57_937269_position_window_restored_not_found](https://user-images.githubusercontent.com/45387203/56567381-748af980-65bd-11e9-8a4e-8619c0ebd943.jpg)


2019-04-23 11:38:03 [INFO] [iris.test_runner] Executing: 1 - [position_window_restored]: Width, height and position of each window are restored.
2019-04-23 11:38:13 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Iris tab is displayed properly
2019-04-23 11:38:23 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: First tab loaded
2019-04-23 11:38:29 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: Second tab loaded
2019-04-23 11:38:33 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 4: Tabs located after size of main window had changed.
2019-04-23 11:38:40 [WARNING] [iris.test_case] >>> FAILED <<< Step 5: Focus webpage content is being displayed - [Actual]: False [Expected]: True 

------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                     <<
>>   File "/Users/ciapa/.local/share/virtualenvs/iris-QV62IM26/bin/iris", line 11, in <module>            <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              <<
>>   File "/Users/ciapa/iris/iris/__main__.py", line 38, in main                                          <<
>>     run_iris()                                                                                         <<
>>   File "/Users/ciapa/iris/iris/__main__.py", line 108, in run_iris                                     <<
>>     run(master_test_list, tests, browser)                                                              <<
>>   File "/Users/ciapa/iris/iris/test_runner.py", line 69, in run                                        <<
>>     current.run()                                                                                      <<
>>   File "/Users/ciapa/iris/iris/tests/session_restore/position_window_restored.py", line 89, in run     <<
>>     assert_true(self, focus_page_content_displayed, 'Focus webpage content is being displayed')        <<
>>   File "/Users/ciapa/iris/iris/asserts.py", line 78, in assert_true                                    <<
>>     assert_equal(test_case, actual, True, message)                                                     <<
>>   File "/Users/ciapa/iris/iris/asserts.py", line 32, in assert_equal                                   <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) <<
------------------------------------------------------------------------------------------------------------

**Comment by tracywalker** [comment]
This test case is disabled on Windows and Linux.  Please investigate and fix.

**Comment by tracywalker** [comment]
This is still failing on Windows and Linux, Please investigate and fix.
