### ISSUE TITLE
Malformed node or string error when submitting Iris report to Testrail

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#3694]
I set up a new Testrail account to test sending Iris reports to Testrail via the Testrail API and ran in to a `malformed node or string` error when Iris tried to submit the report.  In the config file I used the username of the new test account and for the password I used the API key I generated in Testrail with that account.

Here is the output of the error:
```
--------------------------------------------------------- Starting Test Rail report: ----------------------------------------------------------

Starting TestRail reporting.
Traceback (most recent call last):
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/iris/iris_firefox/src/__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/iris_firefox/targets/firefox/main.py", line 129, in pytest_sessionfinish
    report_test_results(self)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 291, in report_test_results
    test_rail_report.create_test_plan(app_test.values['fx_build_id'], app_test.values['fx_version'], test_rail_tests)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 107, in create_test_plan
    suite_runs = self.generate_test_suite_collection_objects(test_case_object_list)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 242, in generate_test_suite_collection_objects
    suite_dictionary = ast.literal_eval(get_config_property('Test_Rail', 'suite_dictionary'))
  File "/usr/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: None

```

**Comment by tracywalker** [comment]
Hmmm.  I'm not sure, but this may be due to the unmaintained suite_dictionary, which I coincidentally noticed yesterday and filed an issue for.  I'll fix that right shortly.

**Comment by tracywalker** [comment]
I've updated the config file suite_dictionary.  Again not sure this will help. Get a fresh pull from dev to give it a try.

**Comment by ashughes1** [comment]
> I've updated the config file suite_dictionary. Again not sure this will help. Get a fresh pull from dev to give it a try.

I got the same error with dev.

**Comment by ashughes1** [comment]
Here is the debug output:
```
2019-08-22 14:13:48 [INFO]  --------------------------------------------------------- Starting Test Rail report: ----------------------------------------------------------

2019-08-22 14:13:48 [INFO] Starting TestRail reporting.
2019-08-22 14:13:48 [DEBUG] Extracting test_rail_url for section Test_rail
2019-08-22 14:13:48 [DEBUG] Extracting username for section Test_rail
2019-08-22 14:13:48 [DEBUG] Extracting password for section Test_rail
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/iris/iris_firefox/src/__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/iris_firefox/targets/firefox/main.py", line 178, in pytest_sessionfinish
    report_test_results(self)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 291, in report_test_results
    test_rail_report.create_test_plan(app_test.values['fx_build_id'], app_test.values['fx_version'], test_rail_tests)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 104, in create_test_plan
    self.run_name = self.generate_test_plan_name(firefox_version)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 221, in generate_test_plan_name
    logger.debug('Creating Test Plan', test_plan_name)
Message: 'Creating Test Plan'
Arguments: ('[Firefox 69.0][Linux]Iris Test Run 2019-08-22',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/coloredlogs/__init__.py", line 1116, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/iris/iris_firefox/src/__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/iris_firefox/targets/firefox/main.py", line 178, in pytest_sessionfinish
    report_test_results(self)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 291, in report_test_results
    test_rail_report.create_test_plan(app_test.values['fx_build_id'], app_test.values['fx_version'], test_rail_tests)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 104, in create_test_plan
    self.run_name = self.generate_test_plan_name(firefox_version)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 221, in generate_test_plan_name
    logger.debug('Creating Test Plan', test_plan_name)
Message: 'Creating Test Plan'
Arguments: ('[Firefox 69.0][Linux]Iris Test Run 2019-08-22',)
2019-08-22 14:13:48 [DEBUG] Extracting suite_dictionary for section Test_Rail
Traceback (most recent call last):
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/iris/iris_firefox/src/__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/_pytest/terminal.py", line 649, in pytest_sessionfinish
    outcome.get_result()
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/iris/.local/share/virtualenvs/iris_firefox-_dt__UE3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/iris/iris_firefox/targets/firefox/main.py", line 178, in pytest_sessionfinish
    report_test_results(self)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 291, in report_test_results
    test_rail_report.create_test_plan(app_test.values['fx_build_id'], app_test.values['fx_version'], test_rail_tests)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 107, in create_test_plan
    suite_runs = self.generate_test_suite_collection_objects(test_case_object_list)
  File "/home/iris/iris_firefox/targets/firefox/testrail/testrail_client.py", line 242, in generate_test_suite_collection_objects
    suite_dictionary = ast.literal_eval(get_config_property('Test_Rail', 'suite_dictionary'))
  File "/usr/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: None
```

**Comment by ashughes1** [comment]
Looks like its failing on Line 242 of testrail_client.py:
`suite_dictionary = ast.literal_eval(get_config_property('Test_Rail', 'suite_dictionary'))`

I did some debugging and `get_config_property('Test_Rail', 'suite_dictionary')` is returning `None` which is perhaps why this is failing. 

Assuming `suite_dictionary` comes from config.ini which I haven't changed from the default as follows:
```
suite_dictionary= {'Bookmark': '75',
                  'History': '2000',
                  'Zoom':'242',
                  'Awesomebar':'1902',
                  'Toolbar':'1998'}
```
I'm not sure why this would return `None`.

**Comment by tracywalker** [comment]
Anthony,  you don't have latest `dev`. 

But as I said before, I don't know if the update I made to suite_dictionary in config.ini would make any difference.  The developers of the Iris integration with TestRail, are no longer on the project.  This is something for core team to look at.
